package com.m2i.model.transaction;

public enum OperationType {
    CREDIT,
    DEBIT,
    TRANSFER,
    PAYMENT,
    WITHDRAWAL,
    DEPOSIT,
    REFUND,
    REWARD, GENESIS, BALANCE, MINI_STATEMENT, STATEMENT, REVERSAL,
      REFUND_CREDIT, REFUND_DEBIT, REFUND_TRANSFER, REFUND_PAYMENT, REFUND_WITHDRAWAL, REFUND_DEPOSIT, REFUND_REWARD, REFUND_GENESIS
}